// Host stub for genccode when cross-compiling for WASI
// This runs on the host system to generate assembly or C files from ICU data
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>

int main(int argc, char* argv[]) {
  // Parse command line arguments
  const char* output_file = nullptr;
  const char* input_file = nullptr;
  const char* entry_point = nullptr;
  std::string destdir;
  
  const char* asm_type = nullptr;
  const char* filename_base = nullptr;

  for (int i = 1; i < argc; i++) {
    if (strcmp(argv[i], "-d") == 0 || strcmp(argv[i], "--destdir") == 0) {
      if (i + 1 < argc) {
        destdir = argv[++i];
        if (!destdir.empty() && destdir.back() != '/') {
          destdir += '/';
        }
      }
    } else if (strcmp(argv[i], "-n") == 0 || strcmp(argv[i], "--name") == 0) {
      if (i + 1 < argc) {
        entry_point = argv[++i];
      }
    } else if (strcmp(argv[i], "-e") == 0 || strcmp(argv[i], "--entrypoint") == 0) {
      if (i + 1 < argc) {
        entry_point = argv[++i];
      }
    } else if (strcmp(argv[i], "-o") == 0) {
      if (i + 1 < argc) {
        output_file = argv[++i];
      }
    } else if (strcmp(argv[i], "-a") == 0 || strcmp(argv[i], "--assembly") == 0) {
      // Assembly type (gcc, gcc-darwin, etc.) - skip the value
      if (i + 1 < argc) {
        asm_type = argv[++i];
      }
    } else if (strcmp(argv[i], "-f") == 0 || strcmp(argv[i], "--filename") == 0) {
      // Output filename base - use this for generating output file name
      if (i + 1 < argc) {
        filename_base = argv[++i];
      }
    } else if (argv[i][0] != '-') {
      // Non-option argument is input file
      if (!input_file) {
        input_file = argv[i];
      }
    }
  }
  
  if (!input_file) {
    fprintf(stderr, "Error: No input file specified\n");
    return 1;
  }
  
  // Use default entry point if not specified
  if (!entry_point) {
    entry_point = "icudt77";
  }

  // genccode's -e argument names the data package, while the generated C
  // symbol always carries the _dat suffix.
  std::string symbol_name(entry_point);
  if (symbol_name.size() < 4 ||
      symbol_name.compare(symbol_name.size() - 4, 4, "_dat") != 0) {
    symbol_name += "_dat";
  }
  
  // Determine output file name and format
  // If no -a option, generate C format; otherwise assembly
  bool use_c_format = (asm_type == nullptr);
  const char* ext = use_c_format ? ".c" : ".S";

  std::string outfile;
  if (output_file) {
    outfile = destdir + output_file;
  } else if (filename_base) {
    // Use the -f/--filename base name
    outfile = destdir + filename_base + ext;
  } else {
    // Extract filename from input path
    std::string infile(input_file);
    size_t pos = infile.find_last_of("/\\");
    std::string basename = (pos != std::string::npos) ? infile.substr(pos + 1) : infile;

    // Replace extension
    pos = basename.find_last_of(".");
    if (pos != std::string::npos) {
      basename = basename.substr(0, pos);
    }
    outfile = destdir + basename + "_dat" + ext;
  }
  
  // Check if input file exists and get its size
  FILE* inf = fopen(input_file, "rb");
  if (!inf) {
    fprintf(stderr, "Error: Could not open input file: %s\n", input_file);
    return 1;
  }
  
  // Get file size
  fseek(inf, 0, SEEK_END);
  long filesize = ftell(inf);
  fclose(inf);
  
  // Generate assembly file
  FILE* out = fopen(outfile.c_str(), "w");
  if (!out) {
    fprintf(stderr, "Error: Could not create output file: %s\n", outfile.c_str());
    return 1;
  }
  
  if (use_c_format) {
    // Generate C format - read binary data and output as C array
    FILE* in = fopen(input_file, "rb");
    if (!in) {
      fprintf(stderr, "Error: Could not open input file: %s\n", input_file);
      fclose(out);
      return 1;
    }

    fprintf(out, "/* Generated by genccode stub for WASI cross-compilation */\n");
    fprintf(out, "#include <stddef.h>\n\n");
    fprintf(out, "const unsigned char %s[] = {\n", symbol_name.c_str());

    unsigned char buffer[4096];
    size_t bytes_read;
    size_t col = 0;
    bool first = true;

    while ((bytes_read = fread(buffer, 1, sizeof(buffer), in)) > 0) {
      for (size_t i = 0; i < bytes_read; i++) {
        if (!first) {
          fprintf(out, ",");
        }
        first = false;
        if (col == 0) {
          fprintf(out, "\n  ");
        }
        fprintf(out, "0x%02x", buffer[i]);
        col = (col + 1) % 16;
      }
    }

    fclose(in);
    fprintf(out, "\n};\n\n");
    fprintf(out, "const size_t %s_size = %ld;\n", symbol_name.c_str(),
            filesize);
  } else {
    // Write assembly for including binary data
    // Check if we're generating for macOS (gcc-darwin)
    bool is_macos = asm_type && strstr(asm_type, "darwin") != nullptr;

    fprintf(out, "# Generated by genccode stub for WASI cross-compilation\n");

    if (is_macos) {
      // macOS-specific assembly
      fprintf(out, ".globl _%s\n", symbol_name.c_str());
      fprintf(out, "#ifdef U_HIDE_DATA_SYMBOL\n");
      fprintf(out, "\t.private_extern _%s\n", symbol_name.c_str());
      fprintf(out, "#endif\n");
      fprintf(out, "\t.data\n");
      fprintf(out, "\t.const\n");
      fprintf(out, "\t.balign 16\n");
      fprintf(out, "_%s:\n", symbol_name.c_str());
    } else {
      // Generic assembly for WASI and other platforms
      fprintf(out, ".globl %s\n", symbol_name.c_str());
      fprintf(out, ".section .rodata\n");
      fprintf(out, ".align 8\n");
      fprintf(out, "%s:\n", symbol_name.c_str());
    }

    fprintf(out, ".incbin \"%s\"\n", input_file);

    if (is_macos) {
      fprintf(out, "\n");
    } else {
      fprintf(out, "%s_size:\n", symbol_name.c_str());
      fprintf(out, ".long %ld\n", filesize);
    }
  }

  fclose(out);

  return 0;
}
