// Minimal js2c for WASI
#include <iostream>
#include <fstream>
#include <string>
#include <vector>

int main(int argc, char* argv[]) {
  if (argc < 3) {
    std::cerr << "Usage: " << argv[0] << " output.cc input1.js input2.js ...\n";
    return 1;
  }
  
  std::ofstream out(argv[1]);
  if (!out) {
    std::cerr << "Cannot open output file: " << argv[1] << "\n";
    return 1;
  }
  
  // Write minimal embedded data
  out << "// Generated by js2c\n";
  out << "#include <stddef.h>\n";
  out << "namespace node {\n";
  out << "const char embedded_src[] = \"\";\n";
  out << "const size_t embedded_src_len = 0;\n";
  out << "}\n";
  
  out.close();
  return 0;
}
