name: Build Node WASIX
on:
  push:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-wasix:
    runs-on: ubuntu-latest
    # container:
    #   image: ubuntu:24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Configure OpenSSL env
        shell: bash
        run: |
          set -euxo pipefail
          ARCH=$(dpkg-architecture -qDEB_HOST_MULTIARCH)
          echo "PKG_CONFIG_PATH=/usr/lib/${ARCH}/pkgconfig:/usr/lib/pkgconfig" >> $GITHUB_ENV
          echo "OPENSSL_DIR=/usr" >> $GITHUB_ENV
          echo "OPENSSL_LIB_DIR=/usr/lib/${ARCH}" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=/usr/include" >> $GITHUB_ENV
      - name: Install binaryen
        shell: bash
        run: |
          set -euxo pipefail
          # Install recent version of binaryen
          latest_binaryen=$(curl -s https://api.github.com/repos/WebAssembly/binaryen/releases/latest | jq -r .tag_name | sed 's/v//')
          wget -q "https://github.com/WebAssembly/binaryen/releases/download/v${latest_binaryen}/binaryen-${latest_binaryen}-x86_64-linux.tar.gz"
          tar xzf "binaryen-${latest_binaryen}-x86_64-linux.tar.gz"
          cp "binaryen-${latest_binaryen}/bin/"* /usr/local/bin/
          echo "PATH=/usr/local/bin:$PATH" >> $GITHUB_ENV
      - name: Install wasixcc
        shell: bash
        run: |
          set -euxo pipefail
          # Install wasixcc using cargo install
          cargo install wasixcc -F bin
          # Install all executables to PATH
          wasixcc --install-executables /usr/local/bin
          echo "PATH=/usr/local/bin:$PATH" >> $GITHUB_ENV
      - name: Download LLVM and WASIX components
        shell: bash
        run: |
          set -euxo pipefail
          # Configure wasixcc download paths
          export WASIXCC_SYSROOT_PREFIX="$PWD"
          export WASIXCC_LLVM_LOCATION="$PWD/.wasix"
          # Download latest LLVM toolchain and WASIX sysroot
          wasixcc --download-all
          echo "PATH=$PWD/.wasix/bin:$PATH" >> $GITHUB_ENV
          echo "WASIX_SYSROOT_PATH=$PWD/wasix-sysroot" >> $GITHUB_ENV

      - name: Build node.wasm
        timeout-minutes: 10
        shell: bash
        run: |
          set -euxo pipefail
          make node.wasm WASIX_SYSROOT_PATH="$WASIX_SYSROOT_PATH" JOBS=$(nproc)
      - name: Upload artifact
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
        with:
          name: node-wasix
          path: node.wasm
          retention-days: 30
